server:
  port: 8083
spring:
  application:
    name: rydo-gateway-service
  cloud:
    gateway:
      routes:
        - id: location-service
          uri: ws://127.0.0.1:8085   # Location Service URL
          predicates:
            - Path=/ws/**
        - id: location-service1
          uri: http://127.0.0.1:8085   # Location Service URL
          predicates:
            - Path=/api/drivers/**
        - id: map-service
          uri: http://127.0.0.1:8084   # User Service URL
          predicates:
            - Path=/api/geo/**
        - id: ride-service
          uri: http://127.0.0.1:8084   # User Service URL
          predicates:
            - Path=/api/rides/**
        - id: user-service
          uri: http://127.0.0.1:8084   # User Service URL
          predicates:
            - Path=/api/users/**
rydo:
  service-url:
    user: http://127.0.0.1:8084
jwt:
  secret: YOUR-256-BIT-SECRET-YOU-MUST-KEEP-SAME-AS-USER-SERVICE
  expirationMs: 7200000 # 1000 * 60 * 60 * 2 # 10 hours